import {z} from 'zod';
import type {PathPoint,VectorClip,VectorElement,VectorGroup} from '../core/vectorScene.js';
import {normalizeScene} from '../core/sceneValidation.js';
import {transformGeometryElement,transformPoint} from '../core/affineTransform.js';
import {polymerPeelawayHero} from './polymerPeelawayHero.js';

const short=z.string().trim().min(1).max(54), panelLine=z.string().trim().min(1).max(20), line=z.string().trim().min(1).max(38), hex=z.string().regex(/^#[0-9A-Fa-f]{6}$/);
export const proposalHybridHeroPlan=z.object({
 schemaVersion:z.literal('ProposalHybridHeroPlan.v1'),profile:z.literal('proposal'),widthMm:z.number().min(85).max(220),seed:z.number().int().min(0).max(4294967295),
 title:z.string().trim().min(1).max(84),subtitle:z.string().trim().min(1).max(138),
 mechanism:z.object({mode:z.enum(['exchange','activation','formulation']),kicker:short,title:panelLine,caption:z.array(panelLine).min(2).max(4),siteLabel:short}).strict(),
 material:z.object({mode:z.enum(['network_library','activation_profile']),kicker:short,upperLabel:short,lowerLabel:short,variantLabels:z.tuple([panelLine,panelLine,panelLine])}).strict(),
 response:z.object({kicker:short,title:short,axisX:panelLine,axisY:panelLine,items:z.tuple([line,line,line])}).strict(),
 decision:z.object({kicker:short,title:z.string().trim().min(1).max(28),question:z.string().trim().min(1).max(12),dataLabel:panelLine,modelLabel:panelLine,noLabel:short,yesLabel:short,outputLabel:short}).strict(),
 controls:z.tuple([short,short,short,short]),footer:z.string().trim().min(1).max(110),caption:z.string().trim().min(1).max(700),altText:z.string().trim().min(1).max(500),sourceRefs:z.array(z.string().trim().min(1)).min(1),
 palette:z.object({teal:hex,deep:hex,orange:hex,muted:hex,paper:hex,line:hex}).strict()
}).strict();
export type ProposalHybridHeroPlan=z.infer<typeof proposalHybridHeroPlan>;

export const defaultProposalHybridHeroPlan:ProposalHybridHeroPlan={schemaVersion:'ProposalHybridHeroPlan.v1',profile:'proposal',widthMm:171.5,seed:429,
 title:'From a coupled formulation library to a tested design map',subtitle:'Measure material state, select kinetic and connectivity contrasts, then test held-out predictions.',
 mechanism:{mode:'formulation',kicker:'01  BUILD',title:'Factorial library',caption:['TBD loading ×','stoichiometry ×','BDGE spacer','= 27 formulations'],siteLabel:'formulation factors'},
 material:{mode:'network_library',kicker:'02  MEASURE MATERIAL STATE',upperLabel:'relaxation τR',lowerLabel:'network connectivity',variantLabels:['RELAXATION','ELASTIC','CONNECTIVITY']},
 response:{kicker:'03  TEST RESPONSE',title:'Measure the response',axisX:'time',axisY:'response',items:['relaxation  •  creep','tensile  •  fracture','reprocessability']},
 decision:{kicker:'04  TEST THE MAP',title:'Does the model explain data?',question:'MATCH?',dataLabel:'HELD-OUT',modelLabel:'FROZEN MODEL',noLabel:'NO: REVISE',yesLabel:'YES',outputLabel:'TRANSFER RULE'},
 controls:['Uncatalyzed reference','Virgin • heated • cut/pressed','Matched thermal history','Predefined held-out cells'],footer:'Prospective schematic — contrasts are selected from measured state, not assumed from recipe.',
 caption:'A 27-formulation library exposes coupled recipe effects. Measured relaxation, elastic state, and connectivity identify kinetic and topology contrasts before property outcomes are examined; a design map advances only after held-out prediction.',altText:'Four-stage proposal schematic. A factorial polymer library is mapped into measured material coordinates, selected contrasts are tested, and only agreement with held-out formulations yields a transferable design map.',
 sourceRefs:['ProposalWriter:2026-nsf-polymers-dynamic-network-mechanistic-map/CAN-narrative-v02.md'],palette:{teal:'#147B7E',deep:'#173B4D',orange:'#B95322',muted:'#566D79',paper:'#F7FAFA',line:'#B9D0D3'}};

const style=(fill:string|null,stroke:string|null,strokeWidth=2,opacity=100)=>({fill,stroke,strokeWidth,opacity,lineCap:'round' as const,lineJoin:'round' as const});
const rect=(e:VectorElement[],id:string,x:number,y:number,width:number,height:number,fill:string|null,z=0,stroke:string|null=null,sw=2)=>e.push({id,type:'rect',x,y,width,height,zIndex:z,style:style(fill,stroke,sw)});
const ellipse=(e:VectorElement[],id:string,x:number,y:number,width:number,height:number,fill:string|null,z=0,stroke:string|null=null,sw=2)=>e.push({id,type:'ellipse',x,y,width,height,zIndex:z,style:style(fill,stroke,sw)});
const path=(e:VectorElement[],id:string,points:Array<[number,number]>,stroke:string,sw=3,z=1,dash?:number[])=>e.push({id,type:'path',x:0,y:0,points:points.map(([x,y])=>({x,y})),closed:false,zIndex:z,style:{fill:null,stroke,strokeWidth:sw,lineCap:'round',lineJoin:'round',...(dash?{dashArray:dash}:{})}});
const text=(e:VectorElement[],id:string,value:string,x:number,y:number,size:number,fill:string)=>e.push({id,type:'text',text:value,x,y,size:Math.max(30,size),font:'DejaVu Sans',zIndex:40,style:{fill,stroke:null}});
function clipTransform(clip:VectorClip,m:{a:number;b:number;c:number;d:number;e:number;f:number}):VectorClip{if(clip.type==='rect'||clip.type==='ellipse')return{...clip,...transformPoint(clip,m),width:clip.width*m.a,height:clip.height*m.d};return{...clip,x:0,y:0,points:clip.points.map(point=>{const p=point as PathPoint,q=transformPoint(p,m),l=p.leftX===undefined?undefined:transformPoint({x:p.leftX,y:p.leftY!},m),r=p.rightX===undefined?undefined:transformPoint({x:p.rightX,y:p.rightY!},m);return{...p,...q,...(l?{leftX:l.x,leftY:l.y}:{}),...(r?{rightX:r.x,rightY:r.y}:{})};})};}

/** Structured semantics choose the story; deterministic components retain authority over geometry. */
export function proposalHybridHero(input:unknown=defaultProposalHybridHeroPlan){
 const plan=proposalHybridHeroPlan.parse(input),{teal,deep,orange,muted,paper,line}=plan.palette,base=polymerPeelawayHero(plan.seed).scene,elements:VectorElement[]=[],groups:VectorGroup[]=[],m={a:.69,b:0,c:0,d:.69,e:360,f:150},prefix='hero.';
 const paints=(base.paints??[]).map(p=>({...p,id:prefix+p.id}));
 for(const g of base.groups??[])groups.push({...g,id:prefix+g.id,parentId:g.parentId?prefix+g.parentId:undefined,...(g.clip?{clip:clipTransform(g.clip,m)}:{})});
 for(const source of base.elements){if(source.id==='hero.title'||source.id==='hero.note'||source.type==='text')continue;const sourceStyle={...source.style,...(source.style?.fillPaint?{fillPaint:prefix+source.style.fillPaint}:{}),...(source.style?.strokePaint?{strokePaint:prefix+source.style.strokePaint}:{})};if(source.type==='rect'||source.type==='ellipse'||source.type==='line'||source.type==='polygon'||source.type==='path'||source.type==='compound_path')elements.push({...transformGeometryElement(source,m),id:prefix+source.id,groupId:source.groupId?prefix+source.groupId:undefined,style:sourceStyle,zIndex:(source.zIndex??0)+10});}
 const arrow=(id:string,a:[number,number],b:[number,number],color=teal)=>{path(elements,id,[a,b],color,4,31);const dx=b[0]-a[0],dy=b[1]-a[1],d=Math.hypot(dx,dy),u:[number,number]=[dx/d,dy/d],n:[number,number]=[-u[1],u[0]];elements.push({id:id+'-head',type:'path',x:0,y:0,closed:true,points:[{x:b[0],y:b[1]},{x:b[0]-15*u[0]+7*n[0],y:b[1]-15*u[1]+7*n[1]},{x:b[0]-15*u[0]-7*n[0],y:b[1]-15*u[1]-7*n[1]}],zIndex:32,style:style(color,null,0)});return[id,id+'-head'];};
 if(plan.material.mode==='network_library'){
  plan.material.variantLabels.forEach((label,i)=>{const x=475+i*225;rect(elements,`hero-variant-${i}`,x,635,210,122,'#FFFFFF',25,line,2);if(i===0){path(elements,'hero-coordinate-relaxation',[[x+22,662],[x+66,672],[x+112,701],[x+174,714]],teal,5,27);path(elements,'hero-coordinate-relaxation-axis',[[x+20,718],[x+20,655],[x+180,655]],muted,2,26);}else if(i===1){path(elements,'hero-coordinate-modulus',[[x+22,675],[x+52,655],[x+82,695],[x+112,655],[x+142,695],[x+178,670]],orange,5,27);path(elements,'hero-coordinate-tg',[[x+25,716],[x+175,716]],teal,8,27);}else{for(let j=0;j<4;j++)path(elements,`hero-coordinate-network-${j}`,[[x+20,660+j*16],[x+75,690-j*5],[x+130,656+j*15],[x+185,684-j*3]],j%2?orange:teal,3,27);for(const [j,cx]of[75,130].entries())ellipse(elements,`hero-coordinate-node-${j}`,x+cx-7,680-j*5,14,14,'#FFFFFF',28,deep,2);}text(elements,`hero-variant-${i}-label`,label,x+8,760,18,deep);});
  text(elements,'hero-variant-constant','MEASURE FIRST  •  THEN SELECT CONTRASTS',475,600,18,deep);
  [[690,350],[830,410],[970,330]].forEach(([x,y],i)=>{ellipse(elements,`hero-swap-${i}`,x-15,y-15,30,30,'#FFFFFF',30,orange,3);path(elements,`hero-swap-${i}-before`,[[x-38,y-15],[x-8,y],[x+15,y-22]],teal,4,31);path(elements,`hero-swap-${i}-after`,[[x-8,y],[x+34,y+17]],orange,4,31);});
 } else{
  const surface=elements.find(e=>e.id==='hero.hero.material.surface');if(surface?.type!=='path')throw Error('Missing transformed material surface');groups.push({id:'hero-profile-clip',zIndex:27,opacity:100,clip:{type:'path',x:0,y:0,points:structuredClone(surface.points),closed:true}});
  elements.push({id:'hero-profile-activated',type:'rect',x:525,y:255,width:760,height:95,groupId:'hero-profile-clip',zIndex:27,style:{fill:orange,stroke:null,opacity:30}},{id:'hero-profile-interphase',type:'rect',x:525,y:350,width:760,height:95,groupId:'hero-profile-clip',zIndex:27,style:{fill:'#D98A57',stroke:null,opacity:23}},{id:'hero-profile-protected',type:'rect',x:525,y:445,width:760,height:150,groupId:'hero-profile-clip',zIndex:27,style:{fill:teal,stroke:null,opacity:14}});
  path(elements,'hero-profile-boundary-top',[[575,350],[1110,350]],orange,3,31,[8,6]);path(elements,'hero-profile-boundary-bottom',[[575,445],[1110,445]],teal,3,31,[8,6]);path(elements,'hero-profile-depth-bracket',[[1130,350],[1160,350],[1160,445],[1130,445]],deep,3,32);text(elements,'hero-profile-depth-label','FINITE ACTIVATION DEPTH',790,570,18,deep);
  for(const [i,x]of[690,850,1010].entries())arrow(`hero-profile-penetration-${i}`,[x,270],[x,350+i*28],orange);
  text(elements,'hero-variant-constant','DIOL FRACTION DECREASES INTO BULK',475,625,18,deep);plan.material.variantLabels.forEach((label,i)=>{const x=475+i*225;rect(elements,`hero-variant-${i}`,x,666,210,88,'#FFFFFF',25,line,2);for(let j=0;j<5-i*2;j++)ellipse(elements,`hero-profile-site-${i}-${j}`,x+25+j*30,684+(j%2)*18,16,16,i===0?orange:i===1?'#D98A57':teal,27);text(elements,`hero-variant-${i}-label`,label,x+8,758,18,deep);});
 }
 rect(elements,'background',0,0,1800,1050,paper,-100);text(elements,'title',plan.title,58,42,38,deep);text(elements,'subtitle',plan.subtitle,58,94,23,teal);
 rect(elements,'mechanism-panel',58,190,320,410,'#FFFFFF',0,line,2);text(elements,'mechanism-kicker',plan.mechanism.kicker,82,216,20,teal);text(elements,'mechanism-title',plan.mechanism.title,82,256,27,deep);path(elements,'chain-left-shadow',[[85,350],[125,320],[166,348]],'#739299',14,3);path(elements,'chain-left',[[85,350],[125,320],[166,348]],teal,8,4);path(elements,'chain-right-shadow',[[212,342],[252,370],[294,340]],'#9D887D',14,3);path(elements,'chain-right',[[212,342],[252,370],[294,340]],orange,8,4);ellipse(elements,'exchange-site',170,326,43,43,'#FFF3E9',6,deep,3);path(elements,'exchange-bond',[[166,348],[170,348]],deep,4,7);path(elements,'exchange-bond-right',[[213,348],[220,342]],deep,4,7);
 rect(elements,'mechanism-reaction-wash',78,292,275,108,'#FFFFFF',8);
 if(plan.mechanism.mode==='exchange'){
  text(elements,'exchange-before','BEFORE',82,294,18,muted);text(elements,'exchange-after','AFTER',247,294,18,muted);
  path(elements,'exchange-before-a',[[88,354],[124,330],[158,350]],teal,7,10);path(elements,'exchange-before-b',[[88,382],[124,360],[158,380]],orange,7,10);ellipse(elements,'exchange-before-site',151,343,18,18,'#FFFFFF',11,deep,3);
  arrow('exchange-event',[174,356],[224,356],orange);
  path(elements,'exchange-after-a',[[238,340],[270,360],[332,326]],orange,7,10);path(elements,'exchange-after-b',[[238,382],[270,360],[332,388]],teal,7,10);ellipse(elements,'exchange-after-site',262,352,18,18,'#FFFFFF',11,deep,3);
 }else if(plan.mechanism.mode==='activation'){
  text(elements,'activation-before','PROTECTED',82,294,18,muted);text(elements,'activation-after','DIOL',274,294,18,muted);ellipse(elements,'protected-site',103,340,54,54,'#FFF3E9',9,orange,3);text(elements,'protected-site-label','P',121,349,18,orange);arrow('activation-input',[171,366],[232,366],orange);ellipse(elements,'activated-oh-left',250,334,40,40,'#FFFFFF',12,teal,3);ellipse(elements,'activated-oh-right',300,370,40,40,'#FFFFFF',12,teal,3);text(elements,'activated-oh-left-label','OH',251,340,17,teal);text(elements,'activated-oh-right-label','OH',301,376,17,teal);
 }else{
  ['TBD','ratio','BDGE'].forEach((label,i)=>{text(elements,`factor-label-${i}`,label,82,296+i*42,18,i===0?orange:deep);for(let j=0;j<3;j++)ellipse(elements,`factor-dot-${i}-${j}`,170+j*28,302+i*42,14,14,j===1?orange:teal,10);});ellipse(elements,'factor-total',278,318,58,58,'#FFF3E9',10,orange,3);text(elements,'factor-total-label','27',288,329,18,orange);
 }
 plan.mechanism.caption.forEach((value,i)=>text(elements,`mechanism-caption-${i}`,value,83,420+i*36,21,i===0?orange:i===1?deep:muted));const chemistryToNetwork=arrow('chemistry-to-network',[387,390],[438,390]);
 rect(elements,'hero-label-wash',518,173,560,55,'#FFFFFF',29);text(elements,'hero-kicker',plan.material.kicker,536,187,21,teal);path(elements,'hero-fast-guide',[[968,292],[1038,260]],orange,2,35,[6,5]);text(elements,'hero-fast-label',plan.material.upperLabel,970,248,19,orange);path(elements,'hero-density-guide',[[704,542],[630,552]],teal,2,35,[6,5]);text(elements,'hero-density-label',plan.material.lowerLabel,496,548,19,teal);const networkToResponse=arrow('network-to-response',[1138,330],[1236,330]);
 rect(elements,'test-panel',1260,190,480,230,'#FFFFFF',0,line,2);text(elements,'test-kicker',plan.response.kicker,1286,216,20,teal);text(elements,'test-title',plan.response.title,1286,256,27,deep);text(elements,'test-axis-y',plan.response.axisY,1278,300,18,muted);path(elements,'test-axis',[[1325,365],[1325,338],[1420,338]],muted,2,3);
 if(plan.material.mode==='network_library'){path(elements,'test-curve-slow',[[1331,342],[1355,345],[1383,352],[1415,357]],teal,3,4);path(elements,'test-curve-base',[[1331,342],[1355,350],[1383,357],[1415,362]],deep,3,4);path(elements,'test-curve-fast',[[1331,342],[1355,355],[1383,362],[1415,364]],orange,3,4);}else path(elements,'test-curve',[[1331,340],[1355,347],[1383,356],[1415,364]],teal,5,4);
 text(elements,'test-axis-x',plan.response.axisX,1345,373,18,muted);plan.response.items.forEach((value,i)=>text(elements,`test-copy-${i}`,value,1460,295+i*40,21,i===2?orange:deep));path(elements,'test-arrow',[[1500,430],[1500,478]],orange,5,10);ellipse(elements,'test-arrow-head',1493,471,14,14,orange,11);
 rect(elements,'decision-panel',1260,488,480,335,'#FFFDFC',0,orange,2);text(elements,'decision-kicker',plan.decision.kicker,1286,512,20,orange);text(elements,'decision-title',plan.decision.title,1286,552,27,deep);
 text(elements,'data-label',plan.decision.dataLabel,1284,604,18,teal);path(elements,'data-curve',[[1438,625],[1464,607],[1492,622],[1522,600]],teal,4,4);
 const modelWords=plan.decision.modelLabel.split(/\s+/);text(elements,'model-label',modelWords[0]!,1284,646,18,orange);if(modelWords[1])text(elements,'model-label-2',modelWords.slice(1).join(' '),1284,682,18,orange);path(elements,'model-curve',[[1438,696],[1464,678],[1492,693],[1522,671]],orange,4,5,[7,5]);
 arrow('compare-data',[1528,612],[1562,632],teal);arrow('compare-model',[1528,684],[1562,654],orange);ellipse(elements,'decision-gate',1560,594,130,130,'#FFFFFF',5,orange,3);text(elements,'decision-question',plan.decision.question,1578,637,21,orange);text(elements,'decision-no',plan.decision.noLabel,1278,730,20,orange);path(elements,'decision-no-arrow',[[1568,702],[1430,727]],orange,4,6);text(elements,'decision-yes',plan.decision.yesLabel,1600,738,20,teal);path(elements,'decision-yes-arrow',[[1625,724],[1625,768]],teal,4,6);rect(elements,'heldout',1430,768,290,38,'#EAF5F3',7,teal,2);text(elements,'heldout-text',plan.decision.outputLabel,1450,775,18,teal);
 rect(elements,'controls',58,858,1684,145,'#FFFFFF',0,line,2);text(elements,'controls-title','CONTROLS',82,878,21,deep);plan.controls.forEach((label,i)=>{const x=i%2?905:276,y=i<2?884:924;ellipse(elements,`control-dot-${i}`,x,y+5,17,17,i===0?orange:teal,5);text(elements,`control-${i}`,label,x+28,y,19,deep);});text(elements,'footer',plan.footer,82,964,20,orange);
 const semantic={objects:[{id:'mechanism',kind:plan.mechanism.mode==='formulation'?'formulation_library':'molecular_mechanism',label:plan.mechanism.title,elementIds:elements.filter(e=>['chain','exchange','activation','factor','protected','activated'].some(p=>e.id?.startsWith(p))).map(e=>e.id!),properties:{illustrative:true,measured:false,depictionOperator:plan.mechanism.mode==='formulation'?'factorial_formulation_design':'molecular_site_schematic',siteLabel:plan.mechanism.siteLabel,sourceRefs:plan.sourceRefs.join(' | ')}},{id:'material',kind:'polymer_material_library',label:plan.material.kicker,elementIds:elements.filter(e=>e.id?.startsWith(prefix)||e.id?.startsWith('hero-')).map(e=>e.id!),properties:{illustrative:true,measured:false,depictionOperator:'illustrative_polymer_cutaway',notToScale:true,seed:plan.seed}},{id:'response',kind:'material_response',label:plan.response.title,elementIds:elements.filter(e=>e.id?.startsWith('test')).map(e=>e.id!),properties:{illustrative:true,measured:false,depictionOperator:'qualitative_response_plot'}},{id:'decision',kind:'held_out_decision',label:plan.decision.title,elementIds:elements.filter(e=>['decision','data','model','heldout'].some(p=>e.id?.startsWith(p))).map(e=>e.id!),properties:{illustrative:true,measured:false,depictionOperator:'held_out_model_gate'}},{id:'controls',kind:'experimental_controls',label:'Controls',elementIds:elements.filter(e=>e.id?.startsWith('control')||e.id==='footer').map(e=>e.id!),properties:{illustrative:true,measured:false,depictionOperator:'experimental_control_legend'}}],relationships:[{id:'mechanism_to_material',sourceObjectId:'mechanism',targetObjectId:'material',predicate:'tunes_material_state',visualElementIds:chemistryToNetwork},{id:'material_to_response',sourceObjectId:'material',targetObjectId:'response',predicate:'is_tested_for_response',visualElementIds:networkToResponse},{id:'response_to_decision',sourceObjectId:'response',targetObjectId:'decision',predicate:'tests_transfer'}]};
 return{plan,scene:normalizeScene({document:{width:1800,height:1050,title:plan.title,colorMode:'RGB'},elements,groups,paints,semantics:semantic}),report:{schemaVersion:'ProposalHybridHero.v2',component:'polymerPeelawayHero.v1',seed:plan.seed,scientificStatus:'conceptual prospective schematic; no measured values'}};
}
